2003-09-27  Eric Blake  <ebb9@email.byu.edu>
	* src/m4/ac_cxx_type_equivalence.m4: New file, needed for at least
	gcc 3.3	on cygwin.
	* Makefile.am: Add dependence on ac_cxx_type_equivalence.m4.
	* acinclude.m4: Ditto.
	* configure.ac: Require automake 1.7.6, and rename from
	configure.in as recommended by automake.
	* Makefile.in: Regenerate.
	* aclocal.m4: Ditto.
	* config.guess: Ditto.
	* config.sub: Ditto.
	* configure: Ditto.
	* depcomp: Ditto.
	* install-sh: Ditto.
	* doc/Makefile.in: Ditto.
	* src/Makefile.in: Ditto.
	* src/config.h.in: Ditto.
	* src/platform.h: Add TYPE_I4_IS_INT to clean up type warnings.
	* src/case.h: Fix type warnings under gcc 3.3.
	* src/double.cpp: Ditto.
	* src/double.h: Ditto.
	* src/long.h: Ditto.
	* src/lookup.cpp: Ditto.
	* src/lookup.h: Ditto.
	* src/stream.cpp: Ditto.

diff --git a/jikes/configure b/jikes/configure
--- a/jikes/configure
+++ b/jikes/configure
@@ -1688,7 +1688,7 @@ INSTALL_STRIP_PROGRAM="\${SHELL} \$(install_sh) -c -s"
 
 
 cat >>confdefs.h <<\_ACEOF
-#define JIKES_VERSION_STRING "Version 1.18b (CVS) - sometime after 18 December 2002"
+#define JIKES_VERSION_STRING "Version 1.18c (CVS) - sometime after 27 September 2003"
 _ACEOF
 
 
@@ -2392,8 +2392,9 @@ DEPDIR="${am__leading_dot}deps"
 
 am_make=${MAKE-make}
 cat > confinc << 'END'
-doit:
+am__doit:
 	@echo done
+.PHONY: am__doit
 END
 # If we don't find an include directive, just comment out the code.
 echo "$as_me:$LINENO: checking for style of include used by $am_make" >&5
@@ -2468,18 +2469,32 @@ else
   # using a relative directory.
   cp "$am_depcomp" conftest.dir
   cd conftest.dir
+  # We will build objects and dependencies in a subdirectory because
+  # it helps to detect inapplicable dependency modes.  For instance
+  # both Tru64's cc and ICC support -MD to output dependencies as a
+  # side effect of compilation, but ICC will put the dependencies in
+  # the current directory while Tru64 will put them in the object
+  # directory.
+  mkdir sub
 
   am_cv_CXX_dependencies_compiler_type=none
   if test "$am_compiler_list" = ""; then
      am_compiler_list=`sed -n 's/^#*\([a-zA-Z0-9]*\))$/\1/p' < ./depcomp`
   fi
   for depmode in $am_compiler_list; do
+    # Setup a source with many dependencies, because some compilers
+    # like to wrap large dependency lists on column 80 (with \), and
+    # we should not choose a depcomp mode which is confused by this.
+    #
     # We need to recreate these files for each test, as the compiler may
     # overwrite some of them when testing with obscure command lines.
     # This happens at least with the AIX C compiler.
-    echo '#include "conftest.h"' > conftest.c
-    echo 'int i;' > conftest.h
-    echo "${am__include} ${am__quote}conftest.Po${am__quote}" > confmf
+    : > sub/conftest.c
+    for i in 1 2 3 4 5 6; do
+      echo '#include "conftst'$i'.h"' >> sub/conftest.c
+      : > sub/conftst$i.h
+    done
+    echo "${am__include} ${am__quote}sub/conftest.Po${am__quote}" > confmf
 
     case $depmode in
     nosideeffect)
@@ -2497,11 +2512,12 @@ else
     # mode.  It turns out that the SunPro C++ compiler does not properly
     # handle `-M -o', and we need to detect this.
     if depmode=$depmode \
-       source=conftest.c object=conftest.o \
-       depfile=conftest.Po tmpdepfile=conftest.TPo \
-       $SHELL ./depcomp $depcc -c -o conftest.o conftest.c \
+       source=sub/conftest.c object=sub/conftest.${OBJEXT-o} \
+       depfile=sub/conftest.Po tmpdepfile=sub/conftest.TPo \
+       $SHELL ./depcomp $depcc -c -o sub/conftest.${OBJEXT-o} sub/conftest.c \
          >/dev/null 2>conftest.err &&
-       grep conftest.h conftest.Po > /dev/null 2>&1 &&
+       grep sub/conftst6.h sub/conftest.Po > /dev/null 2>&1 &&
+       grep sub/conftest.${OBJEXT-o} sub/conftest.Po > /dev/null 2>&1 &&
        ${MAKE-make} -s -f confmf > /dev/null 2>&1; then
       # icc doesn't choke on unknown options, it will just issue warnings
       # (even with -Werror).  So we grep stderr for any message
@@ -19700,7 +19716,77 @@ fi
 
 
 
-if test "$i8" = no; then
+  echo "$as_me:$LINENO: checking whether int32_t and int are equivalent types" >&5
+echo $ECHO_N "checking whether int32_t and int are equivalent types... $ECHO_C" >&6
+if test "${ac_cv_int32_t_is_int+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+    cat >conftest.$ac_ext <<_ACEOF
+
+      #line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+extern void
+foo (int32_t);
+void (*bar) (int) = &foo;
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_int32_t_is_int=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_int32_t_is_int=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+    ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_int32_t_is_int" >&5
+echo "${ECHO_T}$ac_cv_int32_t_is_int" >&6
+  if test $ac_cv_int32_t_is_int = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define TYPE_INT32_T_IS_INT 1
+_ACEOF
+
+fi
+
+
+
+if test "$uint64_t" = no; then
     echo "$as_me:$LINENO: checking whether byte ordering is bigendian" >&5
 echo $ECHO_N "checking whether byte ordering is bigendian... $ECHO_C" >&6
 if test "${ac_cv_c_bigendian+set}" = set; then
@@ -19908,7 +19994,7 @@ esac
 else
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_64BIT_TYPES
+#define HAVE_64BIT_TYPES 1
 _ACEOF
 
 fi
@@ -20079,9 +20165,6 @@ else
 echo "$as_me: error: Could not find stat S_IFDIR symbol" >&2;}
    { (exit 1); exit 1; }; }
 fi
-
-
-
 
 
 
@@ -20469,8 +20552,6 @@ fi
 
 
 
-
-
 # Check whether --with-jikespg or --without-jikespg was given.
 if test "${with_jikespg+set}" = set; then
   withval="$with_jikespg"
@@ -20491,10 +20572,7 @@ fi
 
 
 
-
-
 # Subst variables into Makefile.in to produce the Makefile
-
 
                               ac_config_files="$ac_config_files Makefile doc/Makefile src/Makefile"
 
